name: Mamba Docker Build Benchmark

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image with timing
      run: |
        START_TIME=$(date +%s)
        docker build -t mamba-benchmark .
        END_TIME=$(date +%s)
        BUILD_TIME=$((END_TIME - START_TIME))
        echo "BUILD_TIME=${BUILD_TIME}" >> $GITHUB_ENV
        echo "Build completed in ${BUILD_TIME} seconds"

    - name: Record build time
      run: |
        echo "## Docker Build Time" >> $GITHUB_STEP_SUMMARY
        echo "Total build time: ${BUILD_TIME} seconds" >> $GITHUB_STEP_SUMMARY
        echo "$((BUILD_TIME / 60)) minutes and $((BUILD_TIME % 60)) seconds" >> $GITHUB_STEP_SUMMARY
        echo "### Environment Details" >> $GITHUB_STEP_SUMMARY
        echo "- Base: Ubuntu 22.04" >> $GITHUB_STEP_SUMMARY
        echo "- Package Manager: Mamba (conda-forge)" >> $GITHUB_STEP_SUMMARY
        echo "- Python: 20+ data science packages" >> $GITHUB_STEP_SUMMARY
        echo "- R: 15+ CRAN/Bioconductor packages" >> $GITHUB_STEP_SUMMARY
