name: Long Docker Build Benchmark

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Set timeout to 60 minutes
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image with timing
      run: |
        START_TIME=$(date +%s)
        docker build -t jupyter-mega-image .
        END_TIME
