name: Docker Build Benchmark

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build with cache
      id: build-cache
      run: |
        START_TIME=$(date +%s)
        docker build -t large-image .
        END_TIME=$(date +%s)
        echo "CACHED_BUILD_TIME=$((END_TIME - START_TIME))" >> $GITHUB_ENV
        echo "Cached build: $((END_TIME - START_TIME))s"

    - name: Build without cache
      id: build-no-cache
      run: |
        START_TIME=$(date +%s)
        docker build --no-cache -t large-image .
        END_TIME=$(date +%s)
        echo "NO_CACHE_BUILD_TIME=$((END_TIME - START_TIME))" >> $GITHUB_ENV
        echo "No-cache build: $((END_TIME - START_TIME))s"

    - name: Display timings
      run: |
        echo "-----------------------------"
        echo "Build Time Comparison:"
        echo "Cached build: ${CACHED_BUILD_TIME} seconds"
        echo "No-cache build: ${NO_CACHE_BUILD_TIME} seconds"
        echo "-----------------------------"
        
        echo "## Build Times" >> $GITHUB_STEP_SUMMARY
        echo "- 🟢 Cached build: ${CACHED_BUILD_TIME}s" >> $GITHUB_STEP_SUMMARY
        echo "- 🔴 No-cache build: ${NO_CACHE_BUILD_TIME}s" >> $GITHUB_STEP_SUMMARY
